- README.md
- zplug
* Add link to awesome-zsh-plugins list
* Remove trailing whitespace throughout `README.md`
> Add link to awesome-zsh-plugins list

- zplug
The `clear` command clears the cache, i.e. it removes the `.cache` file.
> add `clear` command to clear cache

- zplug
Suppress the following warning message :snowman:
> Add -C option to compinit

- zplug
Here are the changes discussed in #56.
> Don't force nice value when explicitly specified

- zplug
- Case of #56
- For example, robbyrussell/oh-my-zsh/tree/master/plugins/mix
- This repo consists of only completion file
> Do not load oh-my-zsh.sh if there are no zsh files

- README.md
- zplug
- #56
- `ignore` tag is similar to `of` tag
- the relative path in `ignore` tag will be resolved with respect to the `$ZPLUG_HOME/repos/USER/REPO`
> Implement ignore tag

- zplug
- #65 
- Fix a bug that zplug cannot manage dependencies in case of local plugins
> Enhance dependencies

- zplug
> Rewrite status and fix a bug of OMZ repo

- zplug
> Support multiple plugins of the same name

- zplug
@b4b4r07, @justmytwospence Please test this. It works for me, at least.
> Fix for loop, closes #74 and #88

- zplug
> Fix zplugs from the same directory overwriting previously declared zplugs

- zplug
> Prevent installing packages if conditions are not met

- autoload/commands/__install__
- autoload/commands/__list__
- autoload/commands/__load__
- autoload/commands/__status__
- autoload/commands/__update__
- zplug
With this PR, the names of the packages that failed to install are shown, which helps users figure out what went wrong with the installation.
> Improve messages

- base/sources/local.zsh
> Fix plugins not loaded with multiple from:local

- .gitignore
- autoload/commands/__load__
- base/zplug/variables.zsh
This helped speed up my startup by a bit, as well as allowing the no cache option to be set before you source zplug
> Performance tweaks - zcompile and updating cache in background

- autoload/commands/__load__
- base/zplug/cache.zsh
Follow-up of #104. See https://github.com/zplug/zplug/pull/104#issuecomment-222701579.
> Fix compinit to reproduce zcompdump when it needs

- base/zplug/cache.zsh
> Enable prompt_subst when loading from cache

- autoload/options/__log__
- base/core/core.zsh
> Fix log bug and suppress a verbose log

- README.md
- autoload/commands/__update__
- base/core/add.zsh
- base/core/self.zsh
- doc/guide/ja/README.md
> Fix status code of self updating

- base/base/base.zsh
- base/sources/github.zsh
- base/sources/local.zsh
- base/sources/oh-my-zsh.zsh
- base/utils/omz.zsh
- base/utils/shell.zsh
> Expand glob

- README.md
- doc/guide/ja/README.md
- doc/txt/zplug-update.txt
- doc/zplug.txt
- misc/completions/_zplug
Delete `--self` option from `update` command.
> Delete obsolete option.

- autoload/commands/__check__
- autoload/commands/__install__
- autoload/options/__self-manage__
- base/core/arguments.zsh
- doc/man/man1/zplug-update.1
- doc/man/man1/zplug.1
- misc/completions/_zplug
> Add --self-manage option to zplug instead of update --self

- base/core/load.zsh
- base/job/parallel.zsh
This reverts commit 41869a4a6fb71eec7e8cb3d1c9943174c90da048.
- Related to #338
> Revert "When processing is completed return the monitor option to default"

- base/core/load.zsh
> Restore monitor option to the default when calling load command

- base/core/core.zsh
- base/job/handle.zsh
- base/job/message.zsh
- base/job/parallel.zsh
- base/utils/git.zsh
```console
$ zplug update b4b4r07/enhancd
[zplug] Start to update 1 plugins in parallel
✘  Failed to update      b4b4r07/enhancd
[zplug] Elapsed time: 2.6587 sec.
```
Fix that detached HEAD error:
```console
$ cd $ZPLUG_HOME/repos/b4b4r07/enhancd
$ git rev-parse "@{upstream}"
fatal: HEAD does not point to a branch
```
> Fix not found HEAD error

- base/core/core.zsh
- base/core/load.zsh
- base/job/handle.zsh
- base/job/polling.zsh
- base/log/capture.zsh
- base/log/format.zsh
- base/log/print.zsh
- base/log/write.zsh
> Review log and flock functions

- base/sources/.gitignore
- Fix #333
- See also ./doc/guide/External-Sources.md
> Add local .gitignore file to ignore custom sources

- base/job/parallel.zsh
- base/utils/git.zsh
> Cache clear automatically after running install/update command

- .github/ISSUE_TEMPLATE.md
> Renewal ISSUE_TEMPLATE.md

- README.md
- autoload/commands/__clean__
- base/core/core.zsh
- base/sources/github.zsh
- doc/guide/ja/README.md
> Add environment variable

- base/utils/shell.zsh
https://github.com/zplug/zplug/issues/388
> Protect against infinite recursive fork if python lacks the json module (e.g. older install)

- misc/zshrc
Change S1cK94/minimal -> b4b4r07/ultimate
> update ci script

- .github/ISSUE_TEMPLATE/Bug_report.md
- .github/ISSUE_TEMPLATE/Feature_request.md
About issue and pull request templates - User Documentation
https://help.github.com/articles/about-issue-and-pull-request-templates/
> Update new issue templates

- README.md
Add space to fix 404: Not Found in terminal
> Fix 404: Not Found

- .gitignore
- .zshrc
- Dockerfile
- build.sh
- run.sh
Same as title
It is difficult to check bugs reported by issue etc., and check the operation of the new version zplug. So I'd like to prepare a container that can easily launch a simple elementary environment
> Add Dockerfile for testing zplug

- autoload/options/__log__
- base/core/cache.zsh
- base/io/file.zsh
- base/job/parallel.zsh
- base/job/process.zsh
- base/sources/gh-r.zsh
- base/utils/awk.zsh
- base/utils/releases.zsh
- base/utils/yaml.zsh
- misc/dev/make_tests.zsh
- misc/dev/release.zsh
Fix #464 
@kdheepak Please check this pull request on your machine locally and tell me it's OK to work
> Use unaliased cat
