zplug/zplug

- README.md
Piping scripts delivered over HTTP into your shell opens you up to MITM attacks. HTTPS prevents it.
> Use HTTPS to install in README

- zplug
The `find -depth` option is a boolean, and as such accepts no arguments.
`-maxdepth` is probably what was wanted here.
> Fix clean subcommand

- zplug
`${${(on)nices}#*:}` doesn't sort `nice` correctly since zsh doesn't recognize minus sign as a part of numbers.
> Fix nices sorting

- zplug
I think there is no need to print `Static loading...` every time.
> Print 'Static loading...' only with --verbose

- README.md
`zplug check` has no `--select` option.
> Minor README fix for `check` command

- zplug
On *BSD, the `sleep(1)` command's argument does not allow a unit suffix. The default unit on Linux is seconds anyway, so it's safe to omit.
> Fix sleep(1) argument for BSD

- zplug
I made this change because I think it makes more sense to show the plugins that were **not** loaded only when `--verbose` was used, just like how it is currently for plugins that **were** loaded.
> Suppress "not loaded" message unless --verbose

- zplug
Related to b4b4r07/releases#2.
This change makes it possible to use syntax such as:
```zsh
zplug "junegunn/fzf-bin", \
from:gh-r, \
at:0.10.7, \
as:command, \
of:"*${(L)$(uname -s)}*amd64*", \
file:fzf
```
> Allow specifying version for from:gh-r

- zplug
I found there are some empty directories after removing some plugins.
This prevents `$ZPLUG_HOME/repos` from being cluttered with empty username
directories.
> Remove the username directory if empty after removal of plugin

- zplug
See #79.
```zsh
agross@router ~
$ zplug update
Updating...  zsh-users/zsh-syntax-highlighting
Updating...  rhysd/zsh-bundle-exec
Updating...  agross/rapid-git
Updating...  b4b4r07/zplug
Updating...  bobthecow/git-flow-completion
Updating...  plugins/ssh-agent
Updating...  holman/dotfiles
Up-to-date   rhysd/zsh-bundle-exec              (1.11s)
Up-to-date   b4b4r07/zplug                      (1.15s)
Up-to-date   zsh-users/zsh-syntax-highlighting  (1.38s)
Up-to-date   bobthecow/git-flow-completion      (1.38s)
Up-to-date   holman/dotfiles                    (1.41s)
Updated!     agross/rapid-git                   (1.60s)
Up-to-date   plugins/ssh-agent                  (1.99s)
[4]    27549 done       { trap  INT; local k bg_pid ret=1; local -A zspec; zspec=() ; for k in ; do;
[6]  - 27554 done …
```
> Use HEAD instead of @ and fetch --unshallow on update. Closes #79

- README.md
The difference in the last line is caused by github's editor.
> Correct syntax in sample config.

- zplug
When I run `zplug clean` with no longer managed repositories and there is no deadlinks under `$ZPLUG_HOME/bin/`, an error message is displayed.
```
$ zplug clean
These repositories are no longer managed by zplug.
- ~/.zplug/repos/robbyrussell/oh-my-zsh
Remove? [y/N]: yclean_deadlinks:2: no matches found: ~/.zplug/bin/*(@)
```
So this pull request sets `null_glob` option temporarily in `clean_deadlinks()`, which is explained on [16.2.3 Expansion and Globbing](http://zsh.sourceforge.net/Doc/Release/Options.html#Description-of-Options):
> NULL_GLOB (-G)
>
> If a pattern for filename generation has no matches, delete the pattern from the argument list instead of reporting an error. Overrides NOMATCH.
> Suppress no matches found error

- zplug
This is to ignore packages whose if conditions are evaluated to false when
checking for missing packages. This fixes #96.
> Evaluate the if tag in __zplug::check

- zplug
I tested with GNU grep 2.21 and BSD grep 2.5.1.
Issue #102. This bug is caused by `__version_requirement` expecting a string
that consists of digits and periods but `git --version` outputs a string in
the form `git version X.Y.Z`.
> Fix version check of git

- zplug
Related to #44.
`-C` option skips security checks entirely, and the dump file will only be created if there isn't one already. If we change `-C` to `-i`, then `compinit` will recognize the changes of completion files and produce a new dump file.
See http://zsh.sourceforge.net/Doc/Release/Completion-System.html#Use-of-compinit for details.
Actually I use [zsh-users/zsh-completions](https://github.com/zsh-users/zsh-completions) for completions, and it recently removed brew completion at https://github.com/zsh-users/zsh-completions/commit/173ae7249a6ab4a5b70bebb283f3f156eb79f908. When I run `zplug update` and open a new shell, `brew <Tab>` raises error like:
```
(eval):1: _brew: function definition file not found
(eval):1: _brew: function definition file not found
(eval):1: _brew: function …
```
> Fix compinit to reproduce zcompdump when completion files change

- zplug
Fixed #110 .
Added disabling shwordsplit with localoptions.
> Fixed the wrong behavior of `do tag`

- zplug
The `setopt localoptions` inside the `zplug()` function reverts any change made by any other plugins or themes. This is caused by #111, and the problem of #110 can be solved by quoting arguments of `__zplug::clone` function.
I tested with this `.zshrc`:
``` zsh
setopt shwordsplit
source $HOME/.zplug/zplug
zplug "b4b4r07/hello_bitbucket", \
as:command, \
from:bitbucket, \
do:"chmod 755 *.sh", \
of:"*.sh"
zplug "yous/lime"
zplug check || zplug install
zplug load
```
Note that `yous/lime` [calls `setopt prompt_subst`](https://github.com/yous/lime/blob/master/lime.plugin.zsh) to enable parameter expansion, but `zplug()` reverts that after `zplug load`, prompt will display only `$(prompt_lime_render)`.
With this patch, zplug installs `b4b4r07/hello_bitbucket` with no error messages and the …
> Remove `setopt localoptions`

- lib/support/omz.zsh
This is caused by `&>/dev/null` being separated from the next command, and waits
on EOF from stdin.
1. Run the following:
```console
$ __zplug::support::omz::depends 'plugins/golang'
```
> Fix loading getting stuck in __zplug::support::omz::depends

- zplug
This is due to the expansion `${(%):-%N}` done in an anonymous function.
Fixes #125.
```console
% function() {
echo ${${(%):-%N}:A:h}
}
```
> Fix init.zsh in current directory being sourced

- README.md
- doc/zplug.txt
- lib/zplug/variables.zsh
The value is changed from `$ZPLUG_HOME/init.zsh` to `$ZPLUG_HOME/packages.zsh` to
avoid name collision with the code base.
> Change default value of ZPLUG_LOADFILE

- zplug
Moved from b4b4r07/zplug2#26.
Improvement for a64c511324bf561ba3881849ce6917b65c049c6d.
`${(%):-%x}` is always expanded into the script name.
> Move a declaration of init.zsh path into a function

- README.md
- autoload/commands/__clear__
- doc/man/man1/zplug.1
- doc/zplug.txt
Since there is not much point in prompting (i.e. it's not the end of the world
if you delete your cache by mistake), the default behavior becomes the
equivalent of `--force` but without the message.
> Deprecate clear --force

- autoload/commands/__load__
- doc/zplug/External-Sources.md
- src/ext/local.zsh
This PR fixes some of the bugs in the external source feature and separates `from:local`. Checked with the following:
```zsh
zplug '~/a.zsh', from:local
zplug '~/b.zsh', from:local, as:command
zplug '~/c.zsh', from:local, as:command, rename_to:foo
zplug '~/tmp', from:local
zplug '~/tmp', from:local, as:command, use:a.zsh
```
> Add external source for from:local

- autoload/commands/__load__
- autoload/tags/__rename-to__
- autoload/utils/__add__
- doc/man/man1/zplug.1
- doc/zplug.txt
- src/completions/_zplug
I managed to make the title consist of only two words! :wink: 
Since `hook-build` and `hook-load` both use a hyphen rather than an underscore, `rename_to` is also changed to `rename-to` to follow this naming convention.
@b4b4r07 I am not sure if the second `rename-to` in the following line should be `rename_to` or `rename-to` is fine. I read the zsh documentations on `_values` and it sounded like it's just describing the argument, so my guess was that it's okay for it to be `rename-to`, but could you check to make sure just in case?
https://github.com/NigoroJr/zplug/commit/77a5aa9cdd251b493be10176fb747400a988b49c#diff-3a82ca4b1fcbccf2b113ff0c4f02e94bR96
> Rename rename_to to rename-to

- autoload/commands/__load__
This fixes the error message such as:
```
[zplug] ERROR: pathspec 'master' (at tag) did not match (~/a.zsh)
[zplug] ERROR: pathspec 'master' (at tag) did not match (junegunn/fzf-bin)
```
This is done by blacklisting the from values that are not git repositories,
and avoiding running git checkout on those sources.
> Fix zplug trying to checkout in not-git repo directories

- autoload/utils/__clone__
This fixes the following error:
```
__clone__:cd:157: no such file or directory: path/to/repo
```
, which causes zplug to switch to master branch. The reason why it switches to
master branch on failure needs to be investigated.
This happens, for example, when adding a private bitbucket repository.
> Do not cd into repo directory if clone failed

- autoload/commands/__load__
Even though this is a cosmetic change, it makes the scope of the variable less
confusing. The `load_patterns` variable is only used in the `"plugin"` case of the
case statement, but used outside of the case statement.
> Move assignment from load_patterns into case statement

- autoload/commands/__load__
- autoload/commands/__update__
- src/completions/_zplug
This is due to `$zspec[hook_build]` being used when the correct key is
`$zspec[hook-build]` (with a hyphen).
Checked with:
```zsh
zplug 'zsh-users/zsh-syntax-highlighting', \
hook-build:"echo 'build'", \
hook-load:"echo 'load'"
```
> Fix hook-build and hook-load not evaluated

- autoload/commands/__update__
This is due to an error in git fetch which is ignored because of stderr
redirected to /dev/null. The error can be confirmed with:
$ git fetch ""
which results in the output:
fatal: No path specified. See 'man git-pull' for valid url syntax
Fixes #141.
> Fix zplug update not updating packages

- autoload/commands/__status__
This is due to `%0s` used for specifying the width. When running `zplug status`, error messages like the following is shown:
```
rimraf/k                          (up to date) 'https://git::@github.com/rimraf/k.git'
zsh-users/zsh-syntax-highlightingprintf: %0s: invalid conversion specification
junegunn/fzf-bin                  (up to date) 'https://github.com/junegunn/fzf-bin/releases'
```
> Fix error in printf when running zplug status

- autoload/commands/__load__
Avoid having to have `do:"chmod a=rx *"` on every `as:command` entry.
Signed-off-by: Daniel Bayley <daniel.bayley@me.com>
> Automatically set executable permissions on commands

- autoload/commands/__load__
This fixes the bug where `*.plugin.zsh` is used unconditionally when the file
exists, ignoring the value specified with the use tag.
> Use the value specified with the use tag

- autoload/commands/__install__
For example, when installing `themes/blinks` from oh-my-zsh, the check says
installation failed because `themes/blinks` is a file named `blinks.zsh-theme`.
> Fix incorrect checking of installation results

- autoload/commands/__load__
This is due to the assumption of `$zspec[use]` being empty when the default
value set to it is `*.zsh`. The value set in `zstyle` is queried in case the
default value is changed by the user.
> Fix bug introduced in #157

- autoload/commands/__load__
`.zsh-theme` and `.theme-zsh` files are treated the same way as `.plugin.zsh` files.
Related: #164.
> Source .zsh-theme files by default

- .gitignore
I think the default installation folder of plugins (`$ZPLUG_HOME/repos`) should be registered in `.gitignore`.
> Ignore plugin installation folder

- autoload/commands/__load__
The extensions for themes (`.zsh-theme` and `.theme-zsh` files) are set so that
`setopt prompt_subst` can be run in `__zplug::support::omz::theme`.
Fixes #187.
> Fix prompt_subst not enabled automatically

- base/sources/oh-my-zsh.zsh
As discussed in https://github.com/zplug/zplug/issues/190 this adds the ZSH_CACHE_DIR variable which is used by a number of oh-my-zsh plugins (like the value of cache-path in completion.zsh)
> Added ZSH_CACHE_DIR variable for oh-my-zsh

- autoload/commands/__clear__
These files are stale anyway, and I can see them theoretically causing issues even if the first load will recreate them
> Remove zcompdump files on zplug clear

- base/print/print.zsh
Fix #202 
I have added `LC_ALL=POSIX` to the beginning of `printf` command to solve locale-specific waring.  I will merge this P-R as soon as I can confirm my solution in #202 issue.
> Fix locale-specific warning #202

- autoload/utils/__clone__
The depth tag can conflict with the at tag. A shallow clone may not include the commit/branch/tag specified with the at tag. To avoid confusing users, this PR ignores the depth - forcing a deep clone - when the at tag is used.
To reproduce this issue, specify a shallow clone and an use the at tag with a commit/branch/tag that is not included in the shallow clone. You will get an error `zplug install`. For instance:
```
export ZPLUG_CLONE_DEPTH=1  # Shallow clone for other plugins.
zplug "shvenkat/oh-my-zsh", at:"plugin/shrink-path", use:"plugins/shrink-path/*.zsh"
zplug check || zplug install
zplug load
```
> Do a deep clone if the 'at' tag is used

- base/io/cache.zsh
- Use `autoload`
- Escape or use `command` command <== **adopted**
- Unalias temporary and re-alias
Related to #228
> Unexpand alias in cache

- base/core/core.zsh
DEMO code
```zsh
#!/bin/zsh
unset ZPLUG_ROOT ZPLUG_HOME
path=(
"$ZPLUG_ROOT"/bin
"$ZPLUG_HOME"/bin
"$path[@]"
)
```
Run this script...:
```console
$ zsh a.zsh
/bin
/bin
...
...
```
> Do not add to path if ZPLUG_{ROOT,HOME} are empty

- autoload/commands/__check__
Fix #235. For example if a package has:
```
zplug 'foo/bar', if:false
```
the check should be ignored and `zplug check` should return 0.
```
export ZPLUG_LOADFILE=
export ZPLUG_USE_CACHE=false
source ~/.zplug/init.zsh
zplug "geekjuice/flat-ui-mintty", use:flat-mintty, if:"[[ $OSTYPE == *cygwin* ]]"
zplug check --verbose
echo "Status: $status"
```
```
- geekjuice/flat-ui-mintty: not installed
Status: 1
NigoroMac%
```
```
geekjuice/flat-ui-mintty: (bypassed check)
Status: 0
NigoroMac%
```
> Evaluate IF tag and bypass check if conditions are not met

- base/io/cache.zsh
The `typeset -U path` call in the zplug cache [wipes out the local $PATH](1). The `-gx` options to `typeset` should ensure that the global $PATH variable is still available to functions nice'd >= 10.
[1]: http://www.verycomputer.com/177_fb5233146f3d0cd0_1.htm
* `uname -a`
* `zsh --version`
```
zsh 5.2 (x86_64-apple-darwin15.0.0)
```
* zplug version: 2.2.1
Run twice (once to generate the cache, a second time to use the cachefile).
```zsh
source "$ZPLUG_HOME"/init.zsh
zplug "zsh-users/zsh-completions", nice:11                                                                                                                                      zplug check || zplug install
zplug load --verbose
```
```bash
Static loading...
/Users/Josh/.local/share/zplug/repos/zsh-users/zsh-completions/zsh-comple …
```
> Don't nuke $PATH in cachefile

- base/job/spinner.zsh
With `/dev/stderr`, this fails terribly under sudo, because `/dev/stderr` continues to point to the previous user's fd and the current user likely doesn't have permissions on it. 
So sudo'ing to a user with zplug setup to run, streams errors:
```
__zplug::job::spinner::spin:16: permission denied: /dev/stderr
```
> Redirect output to >&2 instead of /dev/stderr

- autoload/init.zsh
- base/core/core.zsh
See #257 and #258 for background.
I see a huge improvement in startup time, from >200ms to ~80ms, matching with zgen's startup time if zgen itself is sourced.
Comparison:
zgen(load cache file only): 40ms
zgen(load cache file and source zgen.zsh): 80ms
zplug(with this patch): 80ms
zplug(without this patch): 200ms
> Optimize startup time

- doc/man/man1/zplug.1
- doc/txt/zplug.txt
- doc/zplug.txt
Small typo fix in docs / man pages.
> docs: typo fix - replace 'birary' with 'binary'

- base/utils/theme.zsh
Hello.
commit e4d0570eab12de873fcf0ae28fb60919ceafd136 make `git_prompt_info` do nothing without git config oh-my-zsh.hide-status.
But it's different from [oh-my-zsh `git_prompt_info` ](https://github.com/robbyrussell/oh-my-zsh/blob/master/lib/git.zsh).
Then, suppress "not a git repository" message by using 2>/dev/null` like oh-my-zsh's it.
minimum zshrc
```zsh
source ~/.zplug/init.zsh
zplug "b4b4r07/zplug"
#zplug "ywatase/zplug", at:fix_git_prompt_info
zplug check || zplug install
zplug load --verbose
setopt prompt_subst
_get_prompt () {
echo "%~ ${$(git_prompt_info)} \$ "
}
PROMPT='${$(_get_prompt)}'
```
and 
```
cd ~/.zplug/repos/b4b4r07/zplug
```
but don't show `master`
use 
```
zplug "ywatase/zplug", at:fix_git_prompt_info
```
and 
```
cd ~/.zplug/repos/b4b4r07/zplug
```
then show …
> Fix git_prompt_info

- base/core/core.zsh
Between 'deprecated.' with 'Please' should be added a space.
> Add a space between 'deprecated.' with 'Please'

- README.md
- autoload/commands/__list__
- autoload/commands/__status__
- autoload/commands/__update__
- base/utils/shell.zsh
- doc/guide/ja/README.md
- misc/completions/_zplug
- Organize internal specifications
- Add --loaded option to list loaded packages
- Add --installed option to list installed packages
`list` command only lists the contents of $zplugs array.
These options were necessary to list packages such as installed.
> Add some new options to list command

- autoload/commands/__list__
- base/core/load.zsh
- base/job/rollback.zsh
- misc/completions/_zplug
If set globsubst option, this error occur:
```
__list__:92: bad pattern: s/(as|use|at|ignore|lazy|commit|dir|of|rename-to|from|do|defer|file|hook-load|depth|if|nice|frozen|hook-build|on):/^[[33m
```
and several bug fixes
- Fix #350
> Fix "bad pattern" message

- base/sources/gitlab.zsh
- doc/guide/External-Sources.md
- doc/man/man1/zplug.1
- doc/man/man5/zplug-from.5
- doc/txt/zplug-from.txt
- doc/zplug.txt
- misc/completions/_zplug
Pretty much a clone of bitbucket.zsh.
misc/completions/_zplug could be altered to look in base/sources/ for 'zplug from tags'
> Add gitlab support

- base/utils/prezto.zsh
Some prezto modules (like `archive`) don't have a .zsh at all
> load functions-only prezto modules

- README.md
The current recommended installation method has the following problems:
1. It does not explicitly use HTTPS. This means that a attacker can intercept the request before it hits the correct server and hijack it.
2. It uses the `-L` flag, which may redirect to HTTP, and is thus insecure.
To address 1, this commit adds `https://` explicitly to the URL.
To address 2, this commit adds `--proto-redir -all,https`, which forces all redirects to use HTTPS.
From reading #345 I know that https://zplug.sh always uses HTTPS.
However, a user should never have to "trust" that server is correctly configured to use HTTPS, they should interact with it in such a way that if it is not correctly configured, the request will fail.
> Fix security issues with curl installation

- base/io/print.zsh
I found a variable 'i' in zplug is not set to local so users cannot use it on console.
```
> i='aaa'; echo $i
aaa
```
```
> i='aaa'; echo $i
0
```
- Ubuntu 16.04, macOS 10.11
- zsh 5.3.1
This is my first PR. Sorry if I made something wrong.
> Fix global value 'i' to local value

- README.md
The old one-liner is not working now because The domain 'zplug.sh' has expired.
This pull request fix one-liner URL.
> use 'raw.githubusercontent.com' in one-liner

- autoload/options/__self-manage__
Change `$ZPLUG_HOME/repos` to `$ZPLUG_REPOS`.
---
ユーザーによって `$ZPLUG_REPOS` が設定されてる場合 `zplug --self-manage` すると動かなくなるバグを修正しました。
> Fixed bug that `zplug --self-manage` does not work if `$ZPLUG_REPOS` is set.

- base/core/core.zsh
https://github.com/sorin-ionescu/prezto/commits/master
hasn't been maintained since 2016.
I propose zsh-users prezto to be default one since it seems maintained and up to date:
https://github.com/zsh-users/prezto/commits/master
> Changed default prezto repository

- base/core/core.zsh
The previous repo of [prezto](https://github.com/sorin-ionescu/prezto) has been alive, and the forked zsh-users [repo](https://github.com/prezto-inactive-community-fork/prezto) was thus shuted down.
> change prezto repo from zsh-users to sorin-ionescu

- base/core/core.zsh
Fix `ZPLUG_BIN` was not added to `PATH` when `ZPLUG_BIN` was not declared
---
`ZPLUG_BIN` が宣言されていないときに `ZPLUG_BIN` が `PATH` に追加されなかった問題を修正
> $ZPLUG_BIN is not add to $PATH

- base/job/handle.zsh
Since arguments to __zplug::io::print::f are two integers, do not prepend `[zplug]`. Also, use the `proc_states` associative array for length, not the array `repos`.
Without these changes, I get output like this:
```
[zplug] Start to [zplug] update printf: [zplug] 10: expected a numeric value
0 plugins [zplug] in parallel
⠙  Updating...           zsh-users/zsh-completions
⠹  Updating...           zsh-users/zsh-completions-completion
⠸  Updating...           zsh-users/zsh-completions-completion
⠼  Updating...           zsh-users/zsh-completions-completionch
[...]
[zplug] Finished: printf: [zplug] 0: expected a numeric value
0/printf: [zplug] 10: expected a numeric value
0 plugins
```
> Fix printf in __zplug::job::handle::wait

- base/base/base.zsh
Fix for #463 
[hubコマンド](https://github.com/github/hub) のaliasを設定している際に、gitコマンドのバージョンを正常に取得出来なくなるのを修正
> [fix] Fix for #463

- base/base/base.zsh
When git is built from source, the `git version` output contains
non-numeric version components.
```
$ git version
git version 2.24.0.rc2.46.g1d34d425d4
```
zplug cannot detect the git version with this output, and it fails to
start. Change the version pattern to extract a part that starts with a
digit. For the example above, zplug will detect the git version as
"2.24.0.rc2.46.g1d34d425d4". This is good enough for the version check
while there would be no false positives.
> Support git built from source

- README.md
Since `fzf 0.24.0`, it's been moved to `junegunn/fzf`.
This commit fixed its link in the README file.
> Fixed the link to `fzf`

- README.md
Now that code sections in github markdown have copy buttons, it might make sense to remove the prompts from some of them to enable one-click copying.
I wasn't sure about the next code block, since it isn't meant to be copy-paasted as-is (since it has a placeholder)
> remove leading $ from install commands
